Repository GDGoC-Mentos/Mentos-Server, pull requests merged in 2025-02, with the labels that each got.

#3 Feat : 스프링 프로젝트 생성
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mentos/mentosback/MentosBackApplication.java
  src/test/java/com/mentos/mentosback/MentosBackApplicationTests.java
Labels: ⚙ Setting

#9 Feature/users signup
  build.gradle
  src/main/java/com/mentos/mentosback/common/MailService.java
  src/main/java/com/mentos/mentosback/exception/EmailAlreadyExistsException.java
  src/main/java/com/mentos/mentosback/exception/GlobalExceptionHandler.java
  src/main/java/com/mentos/mentosback/security/JwtTokenProvider.java
  src/main/java/com/mentos/mentosback/security/SecurityConfig.java
  src/main/java/com/mentos/mentosback/users/controller/UserController.java
  src/main/java/com/mentos/mentosback/users/dto/UserSignupRequestDto.java
  src/main/java/com/mentos/mentosback/users/entity/Provider.java
  src/main/java/com/mentos/mentosback/users/entity/Role.java
  src/main/java/com/mentos/mentosback/users/entity/Status.java
  src/main/java/com/mentos/mentosback/users/entity/User.java
  src/main/java/com/mentos/mentosback/users/repository/UserRepository.java
  src/main/java/com/mentos/mentosback/users/service/UserService.java
  src/test/java/com/mentos/mentosback/config/ApplicationYamlLoadTest.java
  src/test/java/com/mentos/mentosback/security/JwtTokenProviderTest.java
Labels: ✨ Feature, 🩷예린

#10 [Feature/#6 todo] 할 일, 댓글 관련 기능 추가
  src/main/java/com/mentos/mentosback/comment/controller/CommentController.java
  src/main/java/com/mentos/mentosback/comment/domain/Comment.java
  src/main/java/com/mentos/mentosback/comment/domain/request/CommentRequest.java
  src/main/java/com/mentos/mentosback/comment/domain/response/CommentResponse.java
  src/main/java/com/mentos/mentosback/comment/repository/CommentRepository.java
  src/main/java/com/mentos/mentosback/comment/service/CommentService.java
  src/main/java/com/mentos/mentosback/common/apiPayload/ApiResponse.java
  src/main/java/com/mentos/mentosback/common/apiPayload/code/BaseCode.java
  src/main/java/com/mentos/mentosback/common/apiPayload/code/BaseErrorCode.java
  src/main/java/com/mentos/mentosback/common/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/mentos/mentosback/common/apiPayload/code/ReasonDTO.java
  src/main/java/com/mentos/mentosback/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/mentos/mentosback/common/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/mentos/mentosback/common/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/mentos/mentosback/common/apiPayload/exception/GeneralException.java
  src/main/java/com/mentos/mentosback/todo/controller/TodoController.java
  src/main/java/com/mentos/mentosback/todo/domain/Todo.java
  src/main/java/com/mentos/mentosback/todo/domain/request/DayListRequest.java
  src/main/java/com/mentos/mentosback/todo/domain/request/TodoRequest.java
  src/main/java/com/mentos/mentosback/todo/domain/response/TodoResponse.java
  src/main/java/com/mentos/mentosback/todo/repository/TodoRepository.java
  src/main/java/com/mentos/mentosback/todo/service/TodoService.java
Labels: ✨ Feature, 💙혜진

#12 [Feature/#11 connect-user-category-todo] 할 일, 사용자/카테고리와 연결
  build.gradle
  src/main/java/com/mentos/mentosback/category/CategoryService.java
  src/main/java/com/mentos/mentosback/users/service/UserService.java
Labels: ✨ Feature
